config/routes.rb
Rails.application.routes.draw do
  resources :user_mails

end

app/models/user_mail.rb
class UserMail < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_mails_controller.rb
class UserMailsController < ApplicationController
  before_action :set_user_mail, only: [:show, :edit, :update, :destroy]

  # GET /user_mails
  # GET /user_mails.json
  def index
    @user_mails = UserMail.all
  end

  # GET /user_mails/1
  # GET /user_mails/1.json
  def show
  end

  # GET /user_mails/new
  def new
    @user_mail = UserMail.new
  end

  # GET /user_mails/1/edit
  def edit
  end

  # POST /user_mails
  # POST /user_mails.json
  def create
    @user_mail = UserMail.new(user_mail_params)

    respond_to do |format|
      if @user_mail.save
				UserMailer.welcome_email(@user_mail).deliver
        format.html { redirect_to @user_mail, notice: 'User mail was successfully created.' }
        format.json { render :show, status: :created, location: @user_mail }
      else
        format.html { render :new }
        format.json { render json: @user_mail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_mails/1
  # PATCH/PUT /user_mails/1.json
  def update
    respond_to do |format|
      if @user_mail.update(user_mail_params)
        format.html { redirect_to @user_mail, notice: 'User mail was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_mail }
      else
        format.html { render :edit }
        format.json { render json: @user_mail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_mails/1
  # DELETE /user_mails/1.json
  def destroy
    @user_mail.destroy
    respond_to do |format|
      format.html { redirect_to user_mails_url, notice: 'User mail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_mail
      @user_mail = UserMail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_mail_params
      params.require(:user_mail).permit(:name, :email, :login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_mails_helper.rb
module UserMailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myemail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_mails/_form.html.erb
<%= form_for(@user_mail) do |f| %>
  <% if @user_mail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_mail.errors.count, "error") %> prohibited this user_mail from being saved:</h2>

      <ul>
      <% @user_mail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_mails/edit.html.erb
<h1>Editing user_mail</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_mail %> |
<%= link_to 'Back', user_mails_path %>

app/views/user_mails/index.html.erb
<h1>Listing user_mails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_mails.each do |user_mail| %>
      <tr>
        <td><%= user_mail.name %></td>
        <td><%= user_mail.email %></td>
        <td><%= user_mail.login %></td>
        <td><%= link_to 'Show', user_mail %></td>
        <td><%= link_to 'Edit', edit_user_mail_path(user_mail) %></td>
        <td><%= link_to 'Destroy', user_mail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User mail', new_user_mail_path %>

app/views/user_mails/new.html.erb
<h1>New user_mail</h1>

<%= render 'form' %>

<%= link_to 'Back', user_mails_path %>

app/views/user_mails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_mail.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_mail.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user_mail.login %>
</p>

<%= link_to 'Edit', edit_user_mail_path(@user_mail) %> |
<%= link_to 'Back', user_mails_path %>